# 1. Create a 3x3x3 array with random values


In [2]:
import numpy as np
e=np.random.random(((3,3,3)))
e

array([[[0.80550451, 0.17195667, 0.82203784],
        [0.83456984, 0.31421976, 0.95898951],
        [0.56946121, 0.16553757, 0.36612833]],

       [[0.79466274, 0.36818628, 0.32836962],
        [0.86275319, 0.76494407, 0.94360963],
        [0.34942891, 0.2219652 , 0.33878421]],

       [[0.50056808, 0.20494916, 0.18574729],
        [0.10625587, 0.07834969, 0.89336156],
        [0.07359857, 0.88608049, 0.66199338]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [8]:
import numpy as np
matrix = np.zeros((5, 5))

for i in range(1, 5):
    matrix[i, i-1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern


In [14]:
import numpy as np
matrix = np.zeros((8, 8))
#matrix[1::2] = 1
#matrix[::,1::2] = 1

# Fill the matrix with a checkerboard pattern
matrix[1::2, ::2] = 1  # Rows 2, 4, 6, 8 (0-based indexing) - Odd rows, even columns
matrix[::2, 1::2] = 1  # Rows 1, 3, 5, 7 (0-based indexing) - Even rows, odd columns

print(matrix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [15]:
import numpy as np
random_matrix = np.random.rand(3, 3)

min_value = random_matrix.min()
max_value = random_matrix.max()
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.177134   0.44668744 0.51203261]
 [0.81637106 0.98120685 0.66945876]
 [0.55065369 0.24208221 0.31681319]]

Normalized Matrix:
[[0.         0.3352351  0.41650282]
 [0.79499893 1.         0.61228875]
 [0.46453464 0.08077404 0.1737146 ]]


# 5. How to find common values between two arrays?

In [16]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [19]:
import numpy as np
from datetime import datetime, timedelta

today = datetime.today()

# Convert today's date to a NumPy datetime64 object
today_np = np.datetime64(today)

# Calculate the number of days to add or subtract
one_day = np.timedelta64(1, 'D')

# Calculate yesterday's and tomorrow's dates
yesterday_np = today_np - one_day
tomorrow_np = today_np + one_day

# Convert NumPy datetime64 objects back to datetime objects
yesterday_date = yesterday_np.astype(datetime)
today_date = today_np.astype(datetime)
tomorrow_date = tomorrow_np.astype(datetime)

# Print the dates
print("Yesterday:", yesterday_date)
print("Today:", today_date)
print("Tomorrow:", tomorrow_date)

Yesterday: 2023-09-20 15:37:29.318625
Today: 2023-09-21 15:37:29.318625
Tomorrow: 2023-09-22 15:37:29.318625


# 7. Consider two random array A and B, check if they are equal

In [20]:
import numpy as np

shape = (3, 3)  
A = np.random.rand(*shape) # OR, A=np.random.random((3,3))
B = np.random.rand(*shape)

are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [21]:
import numpy as np

random_vector = np.random.rand(10)
print("Random vector:")
print(random_vector)
print()

max_index = np.argmax(random_vector)
random_vector[max_index] = 0

print("Random vector with maximum value replaced:")
print(random_vector)


Random vector:
[0.10122468 0.9886181  0.6741646  0.89091922 0.52815302 0.85049245
 0.59527102 0.10649462 0.1941274  0.14852486]

Random vector with maximum value replaced:
[0.10122468 0.         0.6741646  0.89091922 0.52815302 0.85049245
 0.59527102 0.10649462 0.1941274  0.14852486]


# 9. How to print all the values of an array?

In [22]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

print(my_array)

[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [26]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1)
print("Mean of each row: ",row_means)

resultant_matrix = matrix - row_means[:, np.newaxis]

print("\nOriginal Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(resultant_matrix)

Mean of each row:  [2. 5. 8.]

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [31]:
import numpy as np

given_vector = np.array([1, 2, 3, 4, 5])

indices_vector = np.array([0, 2, 2, 4])

result_vector = np.zeros_like(given_vector)
print("Result Vector before adding 1:\n", result_vector)

for index in indices_vector:
    result_vector[index] += 1

print("Given Vector:", given_vector)
print("Result Vector:", result_vector) # at index 2 adding 1 is two times....see carefully


Result Vector before adding 1:
 [0 0 0 0 0]
Given Vector: [1 2 3 4 5]
Result Vector: [1 0 2 0 1]


# 12.How to get the diagonal of a dot product?

In [33]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

dot_product = np.dot(A, B)

diagonal = np.diag(dot_product)

print("Matrix A:")
print(A)
print()
print("Matrix B:")
print(B)
print()
print("Dot Product of A and B:")
print(dot_product)
print()
print("Diagonal of the Dot Product:")
print(diagonal)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Dot Product of A and B:
[[19 22]
 [43 50]]

Diagonal of the Dot Product:
[19 50]


# 13.How to find the most frequent value in an array?

In [34]:
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Use numpy.bincount() to count occurrences of each value
counts = np.bincount(arr)

# Find the value with the highest count
most_frequent_value = np.argmax(counts)

print("Array:", arr)
print("Most frequent value:", most_frequent_value)

Array: [1 2 2 3 3 3 4 4 4 4]
Most frequent value: 4


# 14.How to get the n largest values of an array

In [37]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

n = 3
# Use numpy.partition to partially sort the array and get the n largest values
n_largest_values = np.partition(arr, -n)[-n:]

print("Array:", arr)
print(f"{n} Largest Values:", n_largest_values)

Array: [3 1 4 1 5 9 2 6 5 3 5]
3 Largest Values: [5 6 9]


# 15.How to create a record array from a regular array?

In [38]:
import numpy as np

regular_array = np.array([[1, 'John', 25],
                          [2, 'Alice', 30],
                          [3, 'Bob', 28]])

dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create a record array from the regular array
record_array = np.rec.fromarrays(regular_array.T, dtype=dtype)

print(record_array)

[(1, 'John', 25) (2, 'Alice', 30) (3, 'Bob', 28)]


# 16. How to swap two rows of an array?

In [41]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Define the indices of the rows you want to swap
row1_index = 0
row2_index = 2
print("Original Array:")
print(arr)

temp_row = arr[row1_index].copy()  
arr[row1_index] = arr[row2_index]   
arr[row2_index] = temp_row         

print("\nSwapped Array:")
print(arr)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Swapped Array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [43]:
#2d data
from numpy import array
data=array([[11,22],[33,44],[55,66]])
print(data,data.shape,data.ndim)

[[11 22]
 [33 44]
 [55 66]] (3, 2) 2


In [44]:
# 2d to 3d
d2=data.reshape((data.shape[0],data.shape[1],1))
print(d2)
print()
print(d2.shape)
print()
print(d2.ndim)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]

(3, 2, 1)

3
